----테이블 drop----

DROP TABLE BB_ADMIN
CASCADE CONSTRAINTS;

DROP TABLE BB_STORE
CASCADE CONSTRAINTS;

DROP TABLE BB_MEMBER
CASCADE CONSTRAINTS;

DROP TABLE BB_ADDR
CASCADE CONSTRAINTS;

DROP TABLE BB_ORDER
CASCADE CONSTRAINTS;

DROP TABLE BB_ORDERMENU
CASCADE CONSTRAINTS;

DROP TABLE BB_FAVORITE
CASCADE CONSTRAINTS;

DROP TABLE BB_FAVORITEMENU
CASCADE CONSTRAINTS;


DROP TABLE BB_MENU
CASCADE CONSTRAINTS;

DROP TABLE BB_BURGER
CASCADE CONSTRAINTS;

DROP TABLE BB_INGREDIENT
CASCADE CONSTRAINTS;

DROP TABLE BB_BEVERAGE
CASCADE CONSTRAINTS;

DROP TABLE BB_SIDE
CASCADE CONSTRAINTS;

DROP TABLE BB_BBS
CASCADE CONSTRAINTS;

DROP TABLE BB_LIKE
CASCADE CONSTRAINTS;

DROP TABLE BB_IMAGE
CASCADE CONSTRAINTS;

DROP TABLE BB_FAQ
CASCADE CONSTRAINTS;

DROP TABLE BB_INQUIRY
CASCADE CONSTRAINTS;

------seqdrop----

DROP SEQUENCE BB_ADMIN_SEQ;

DROP SEQUENCE BB_STORE_SEQ;

DROP SEQUENCE BB_MEMBER_SEQ;

DROP SEQUENCE BB_ADDR_SEQ;

DROP SEQUENCE BB_ORDER_SEQ;

DROP SEQUENCE BB_ORDERMENU_SEQ;

DROP SEQUENCE BB_FAVORITE_SEQ;

DROP SEQUENCE BB_FAVORITEMENU_SEQ;

DROP SEQUENCE BB_MENU_SEQ;

DROP SEQUENCE BB_BURGER_SEQ;

DROP SEQUENCE BB_INGREDIENT_SEQ;

DROP SEQUENCE BB_BEVERAGE_SEQ;

DROP SEQUENCE BB_SIDE_SEQ;

DROP SEQUENCE BB_BBS_SEQ;

DROP SEQUENCE BB_LIKE_SEQ;

DROP SEQUENCE BB_IMAGE_SEQ;

DROP SEQUENCE BB_FAQ_SEQ;

DROP SEQUENCE BB_INQUIRY_SEQ;

--------------------------------테이블생성------------------------------------

CREATE TABLE BB_ADMIN(
  SEQ NUMBER(10) PRIMARY KEY,
  ID VARCHAR2(20) UNIQUE,
  PASSWORD VARCHAR2(20) NOT NULL,
  NAME VARCHAR2(20) NOT NULL,
  PHONE VARCHAR2(20) NOT NULL,
  STORE_SEQ NUMBER(10) NOT NULL,
  DEL NUMBER(1) NOT NULL
);

CREATE TABLE BB_STORE(
  SEQ NUMBER(10) PRIMARY KEY,
  NAME VARCHAR2(100) NOT NULL,
  PHONE VARCHAR2(20) NOT NULL,
  ADDRESS VARCHAR2(500) NOT NULL,
  LAT VARCHAR2(100) NOT NULL,
  LNG VARCHAR2(100) NOT NULL,
  DEL NUMBER(1) NOT NULL
);


CREATE TABLE BB_MEMBER(
  SEQ NUMBER(10) PRIMARY KEY,
  ID VARCHAR2(20) NOT NULL,
  PASSWORD VARCHAR2(20) NOT NULL,
  BDAY VARCHAR2(20) NOT NULL,
  NAME VARCHAR2(20) NOT NULL,
  PHONE VARCHAR2(20) NOT NULL,
  SEX NUMBER(1) NOT NULL,
  MILEAGE NUMBER(10) NOT NULL,
  GRADE NUMBER(10) NOT NULL,
  EXP NUMBER(10) NOT NULL,
  DEL NUMBER(1) NOT NULL
);



CREATE TABLE BB_ADDR(
  SEQ NUMBER(10) PRIMARY KEY,
  MEMBER_SEQ NUMBER(10) NOT NULL,
  ADDRESS VARCHAR2(500) NOT NULL,
  LAT VARCHAR2(100) NOT NULL,
  LNG VARCHAR2(100) NOT NULL,
  MEMO VARCHAR2(200),
  DEL NUMBER(1) NOT NULL
);


CREATE TABLE BB_ORDER(
  SEQ NUMBER(10) PRIMARY KEY,
  MEMBER_SEQ NUMBER(10) NOT NULL,
  MEMBER_ADDR NUMBER(10),
  STORE_SEQ NUMBER(10),
  ORDER_DATE DATE NOT NULL,
  STATUS NUMBER(1) NOT NULL,
      PRICE NUMBER(20) NOT NULL,
  DEL NUMBER(1) NOT NULL
);



CREATE TABLE BB_ORDERMENU(
  SEQ NUMBER(10) PRIMARY KEY,
  ORDER_SEQ NUMBER(10) NOT NULL,
  MENU_SEQ NUMBER(10) NOT NULL,
  QUANTITY NUMBER(4) NOT NULL,
  DEL NUMBER(1) NOT NULL
);


CREATE TABLE BB_FAVORITE(
  SEQ NUMBER(10) PRIMARY KEY,
  MEMBER_SEQ NUMBER(10) NOT NULL,
  DEL NUMBER(1) NOT NULL,
    PRICE NUMBER(10) NOT NULL
);


CREATE TABLE BB_FAVORITEMENU(
  SEQ NUMBER(10) PRIMARY KEY,
  FAVORITE_SEQ NUMBER(10) NOT NULL,
  MENU_SEQ NUMBER(10) NOT NULL,
  QUANTITY NUMBER(4) NOT NULL,
  DEL NUMBER(1) NOT NULL,
    PRICE NUMBER(10) NOT NULL
);


CREATE TABLE BB_MENU(
  SEQ NUMBER(10) PRIMARY KEY,
  BURGER NUMBER(10) NOT NULL,
  SIDE NUMBER(10) NOT NULL,
  BEVERAGE NUMBER(10) NOT NULL,
  NAME VARCHAR2(100) NOT NULL,
  CREATOR NUMBER(20) NOT NULL,
  PRICE NUMBER(20) NOT NULL,
  CAL NUMBER(20) NOT NULL,
  DEL NUMBER(1) NOT NULL
);


CREATE TABLE BB_BURGER(
  SEQ NUMBER(10) PRIMARY KEY,
  NAME VARCHAR2(100) NOT NULL,
  BREAD NUMBER(10) NOT NULL,
  INGREDIENT01 NUMBER(10) NOT NULL,
  INGREDIENT02 NUMBER(10) NOT NULL,
  INGREDIENT03 NUMBER(10) NOT NULL,
  INGREDIENT04 NUMBER(10) NOT NULL,
  INGREDIENT05 NUMBER(10) NOT NULL,
  INGREDIENT06 NUMBER(10) NOT NULL,
  INGREDIENT07 NUMBER(10) NOT NULL,
  INGREDIENT08 NUMBER(10) NOT NULL,
  INGREDIENT09 NUMBER(10) NOT NULL,
  CREATOR NUMBER(10) NOT NULL,
  PRICE NUMBER(20) NOT NULL,
  CAL NUMBER(20) NOT NULL,
  DEL NUMBER(1) NOT NULL
);

CREATE TABLE BB_INGREDIENT(
  SEQ NUMBER(10) PRIMARY KEY,
  NAME VARCHAR2(100) NOT NULL,
  TYPES NUMBER(1) NOT NULL,
  PRICE NUMBER(20) NOT NULL,
  CAL NUMBER(20) NOT NULL,
  DEL NUMBER(1) NOT NULL
);

CREATE TABLE BB_BEVERAGE(
  SEQ NUMBER(10) PRIMARY KEY,
  NAME VARCHAR2(100) NOT NULL,
  PRICE NUMBER(20) NOT NULL,
  CAL NUMBER(20) NOT NULL,
  DEL NUMBER(1) NOT NULL
);

CREATE TABLE BB_SIDE(
  SEQ NUMBER(10) PRIMARY KEY,
  NAME VARCHAR2(100) NOT NULL,
  PRICE NUMBER(20) NOT NULL,
  CAL NUMBER(20) NOT NULL,
  DEL NUMBER(1) NOT NULL
);


CREATE TABLE BB_BBS(
  SEQ NUMBER(10) PRIMARY KEY,
  BURGER_SEQ NUMBER(10) NOT NULL,
  WRITER NUMBER(10) NOT NULL,
  BBS_LIKE NUMBER(10) NOT NULL,
  DEL NUMBER(1) NOT NULL
);


CREATE TABLE BB_LIKE(
  SEQ NUMBER(10) PRIMARY KEY,
  MEMBER_SEQ NUMBER(20) NOT NULL,
  BBS_SEQ NUMBER(10) NOT NULL
);

CREATE TABLE BB_IMAGE(
  SEQ NUMBER(10) PRIMARY KEY,
  TABLE_NAME VARCHAR2(100) NOT NULL,
  WHAT_IMAGE VARCHAR2(100) NOT NULL,
  IMAGE_SRC VARCHAR2(100) NOT NULL,
  REF_SEQ NUMBER(10) NOT NULL,
  DEL NUMBER(1) NOT NULL
);

CREATE TABLE BB_FAQ(
   SEQ NUMBER(10) PRIMARY KEY,
   TITLE VARCHAR2(200) NOT NULL,
   CONTENTS VARCHAR2(300) NOT NULL,
   CATEGORIES NUMBER(5) NOT NULL,
   READCOUNT NUMBER(10) NOT NULL,
   STEP NUMBER(10) NOT NULL,
   GROUPS NUMBER(10) NOT NULL,
   STATUS NUMBER(1) NOT NULL,
   REGDATE DATE,
   DEL NUMBER(1) NOT NULL
);


CREATE TABLE BB_INQUIRY(
   SEQ NUMBER(10),
   TITLE VARCHAR2(100),
   EMAIL VARCHAR2(50),
   REGDATE DATE,
   CONTENT VARCHAR2(4000),
   STATUS NUMBER(2)
);
--------------------------------시퀀스생성------------------------------------
CREATE SEQUENCE BB_ADMIN_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE BB_STORE_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE BB_MEMBER_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE BB_ADDR_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE BB_ORDER_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE BB_ORDERMENU_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE BB_FAVORITE_SEQ
START WITH 1
INCREMENT BY 1;


CREATE SEQUENCE BB_FAVORITEMENU_SEQ
START WITH 1
INCREMENT BY 1;


CREATE SEQUENCE BB_MENU_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE BB_BURGER_SEQ
START WITH 1
INCREMENT BY 1;


CREATE SEQUENCE BB_INGREDIENT_SEQ
START WITH 1
INCREMENT BY 1;


CREATE SEQUENCE BB_BEVERAGE_SEQ
START WITH 1
INCREMENT BY 1;


CREATE SEQUENCE BB_SIDE_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE BB_BBS_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE BB_LIKE_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE BB_IMAGE_SEQ
START WITH 1
INCREMENT BY 1;


CREATE SEQUENCE BB_FAQ_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE BB_INQUIRY_SEQ
START WITH 1
INCREMENT BY 1;

-------------------------------외래키로연결


--BB_ADMIN

ALTER TABLE BB_ADMIN
ADD CONSTRAINT FK_BB_STORE_SEQ FOREIGN KEY(STORE_SEQ)
REFERENCES BB_STORE(SEQ);

ALTER TABLE BB_ADDR
ADD CONSTRAINT FK_BB_M_ADDR_SEQ FOREIGN KEY(MEMBER_SEQ)
REFERENCES BB_MEMBER(SEQ);

ALTER TABLE BB_FAVORITE
ADD CONSTRAINT FK_BB_M_FAVORITE_SEQ FOREIGN KEY(MEMBER_SEQ)
REFERENCES BB_MEMBER(SEQ);

ALTER TABLE BB_FAVORITEMENU
ADD CONSTRAINT FK_BB_F_FAVORITEMENU_SEQ FOREIGN KEY(FAVORITE_SEQ)
REFERENCES BB_FAVORITE(SEQ);

ALTER TABLE BB_ORDER
ADD CONSTRAINT FK_BB_MS_ORDER_SEQ FOREIGN KEY(MEMBER_SEQ)
REFERENCES BB_MEMBER(SEQ);

ALTER TABLE BB_ORDER
ADD CONSTRAINT FK_BB_AS_ORDER_SEQ FOREIGN KEY(MEMBER_ADDR)
REFERENCES BB_ADDR(SEQ);

ALTER TABLE BB_ORDER
ADD CONSTRAINT FK_BB_SS_ORDER_SEQ FOREIGN KEY(STORE_SEQ)
REFERENCES BB_STORE(SEQ);

ALTER TABLE BB_ORDERMENU
ADD CONSTRAINT FK_BB_O_ORDERMENU_SEQ FOREIGN KEY(ORDER_SEQ)
REFERENCES BB_ORDER(SEQ);

ALTER TABLE BB_ORDERMENU
ADD CONSTRAINT FK_BB_M_ORDERMENU_SEQ FOREIGN KEY(MENU_SEQ)
REFERENCES BB_MENU(SEQ);

ALTER TABLE BB_MENU
ADD CONSTRAINT FK_BB_BURGER_MENU_SEQ FOREIGN KEY(BURGER)
REFERENCES BB_BURGER(SEQ);

ALTER TABLE BB_MENU
ADD CONSTRAINT FK_BB_SIDE_MENU_SEQ FOREIGN KEY(SIDE)
REFERENCES BB_SIDE(SEQ);

ALTER TABLE BB_MENU
ADD CONSTRAINT FK_BB_BEVERAGE_MENU_SEQ FOREIGN KEY(BEVERAGE)
REFERENCES BB_BEVERAGE(SEQ);

ALTER TABLE BB_BBS
ADD CONSTRAINT FK_BB_BURGER_BBS_SEQ FOREIGN KEY(BURGER_SEQ)
REFERENCES BB_BURGER(SEQ);

ALTER TABLE BB_BURGER
ADD CONSTRAINT FK_BB_INGRE_BURGER_SEQ FOREIGN KEY(INGREDIENT01)
REFERENCES BB_INGREDIENT(SEQ);

ALTER TABLE BB_BURGER
ADD CONSTRAINT FK_BB_INGRE02_BURGER_SEQ FOREIGN KEY(INGREDIENT02)
REFERENCES BB_INGREDIENT(SEQ);

ALTER TABLE BB_BURGER
ADD CONSTRAINT FK_BB_INGRE03_BURGER_SEQ FOREIGN KEY(INGREDIENT03)
REFERENCES BB_INGREDIENT(SEQ);

ALTER TABLE BB_BURGER
ADD CONSTRAINT FK_BB_INGRE04_BURGER_SEQ FOREIGN KEY(INGREDIENT04)
REFERENCES BB_INGREDIENT(SEQ);

ALTER TABLE BB_BURGER
ADD CONSTRAINT FK_BB_INGRE05_BURGER_SEQ FOREIGN KEY(INGREDIENT05)
REFERENCES BB_INGREDIENT(SEQ);

ALTER TABLE BB_BURGER
ADD CONSTRAINT FK_BB_INGRE06_BURGER_SEQ FOREIGN KEY(INGREDIENT06)
REFERENCES BB_INGREDIENT(SEQ);

ALTER TABLE BB_BURGER
ADD CONSTRAINT FK_BB_INGRE_BURGER07_SEQ FOREIGN KEY(INGREDIENT07)
REFERENCES BB_INGREDIENT(SEQ);

ALTER TABLE BB_BURGER
ADD CONSTRAINT FK_BB_INGRE_BURGER08_SEQ FOREIGN KEY(INGREDIENT08)
REFERENCES BB_INGREDIENT(SEQ);

ALTER TABLE BB_BURGER
ADD CONSTRAINT FK_BB_INGRE_BURGER09_SEQ FOREIGN KEY(INGREDIENT09)
REFERENCES BB_INGREDIENT(SEQ);

ALTER TABLE BB_BURGER
ADD CONSTRAINT FK_BB_INGRE_BURGER10_SEQ FOREIGN KEY(BREAD)
REFERENCES BB_INGREDIENT(SEQ);


-----------기본값으로 넣어둬야하는거

---1)재료 0번(선택안함)
INSERT INTO BB_INGREDIENT(SEQ,NAME,TYPES,PRICE,CAL,DEL)
VALUES(0,'x',0,0,0,0);

----2)관리자가만든버거 creator 0번으로 들어감
insert into bb_member
values(0, 'admin', 'admin', 'admin', 'admin','admin', 0, 0, 0, 0, 0);

----3)seq 를 0번으로 본사 등록
INSERT INTO BB_STORE(SEQ, NAME, PHONE, ADDRESS, LAT, LNG, DEL)
VALUES ( 0,'본사', '123-1234-1234', '본사', 1, 1, 0 );

----4)관리자계정(총관리자)
INSERT INTO BB_ADMIN(SEQ, ID, PASSWORD, NAME, PHONE, STORE_SEQ, DEL)
VALUES ( BB_ADMIN_SEQ.NEXTVAL,'admin', 'admin', 'admin', '111-1111-1111', 0, 0 );

--커밋
commit;