SELECT A.SEQ, A.NAME, 
A.CREATOR , A.PRICE, A.CAL,A.DEL ,NVL(B.IMAGE_SRC, '없음') IMAGE_SRC,
A.BREAD, 
A.INGREDIENT01, A.INGREDIENT02, A.INGREDIENT03,
A.INGREDIENT04,A.INGREDIENT05,A.INGREDIENT06,
A.INGREDIENT07,A.INGREDIENT08,A.INGREDIENT09, NVL(C.NAME, '0') creatorID,
(SELECT NAME FROM BB_INGREDIENT WHERE SEQ=A.BREAD) BREAD_NAME,
(SELECT NAME FROM BB_INGREDIENT WHERE SEQ=A.INGREDIENT01) INGREDIENT01_NAME,
(SELECT NAME FROM BB_INGREDIENT WHERE SEQ=A.INGREDIENT02) INGREDIENT02_NAME,
(SELECT NAME FROM BB_INGREDIENT WHERE SEQ=A.INGREDIENT03) INGREDIENT03_NAME,
(SELECT NAME FROM BB_INGREDIENT WHERE SEQ=A.INGREDIENT04) INGREDIENT04_NAME,
(SELECT NAME FROM BB_INGREDIENT WHERE SEQ=A.INGREDIENT05) INGREDIENT05_NAME,
(SELECT NAME FROM BB_INGREDIENT WHERE SEQ=A.INGREDIENT06) INGREDIENT06_NAME,
(SELECT NAME FROM BB_INGREDIENT WHERE SEQ=A.INGREDIENT07) INGREDIENT07_NAME,
(SELECT NAME FROM BB_INGREDIENT WHERE SEQ=A.INGREDIENT08) INGREDIENT08_NAME,
(SELECT NAME FROM BB_INGREDIENT WHERE SEQ=A.INGREDIENT09) INGREDIENT09_NAME
FROM BB_BURGER A, (SELECT * FROM BB_IMAGE WHERE TABLE_NAME='BB_BURGER') B, BB_MEMBER C
WHERE A.SEQ = B.REF_SEQ(+)
AND A.CREATOR = C.SEQ(+)
ORDER BY SEQ 

SELECT NVL(SUM(PRICE), 0) 
FROM BB_ORDER 
WHERE ORDER_DATE BETWEEN  
(Select trunc(add_months(sysdate,-1)) - (to_number(to_char(add_months(sysdate,-1),'DD')) - 1) FROM dual)  
AND  
(SELECT add_months(trunc(add_months(sysdate,-1)) - (to_number(to_char(add_months(sysdate,-1),'DD')) - 1), 1) -1 FROM dual)