/* 재료 테이블 */

SELECT * FROM BB_INGREDIENT;

DROP TABLE BB_INGREDIENT
CASCADE CONSTRAINT;

DROP SEQUENCE BB_INGREDIENT;

CREATE TABLE BB_INGREDIENT(
  SEQ NUMBER(10) PRIMARY KEY,
  NAME VARCHAR2(100) NOT NULL,
  INGREDIENT_TYPE NUMBER(1) NOT NULL,
  PRICE NUMBER(20) NOT NULL,
  CAL NUMBER(20) NOT NULL,
  DEL NUMBER(1) NOT NULL
)

CREATE SEQUENCE BB_INGREDIENT_SEQ
START WITH 1
INCREMENT BY 1;

INSERT INTO BB_INGREDIENT
VALUES(BB_INGREDIENT_SEQ.NEXTVAL, '호밀번', 1, 500, 120, 0);

INSERT INTO BB_INGREDIENT
VALUES(BB_INGREDIENT_SEQ.NEXTVAL, '밀번', 1, 400, 140, 0);

INSERT INTO BB_INGREDIENT
VALUES(BB_INGREDIENT_SEQ.NEXTVAL, '흑미번', 1, 600, 90, 0);

INSERT INTO BB_INGREDIENT
VALUES(BB_INGREDIENT_SEQ.NEXTVAL, '소고기패티', 2, 1000, 160, 0);

INSERT INTO BB_INGREDIENT
VALUES(BB_INGREDIENT_SEQ.NEXTVAL, '스테이크패티', 2, 1300, 180, 0);

INSERT INTO BB_INGREDIENT
VALUES(BB_INGREDIENT_SEQ.NEXTVAL, '치킨패티', 2, 800, 200, 0);

INSERT INTO BB_INGREDIENT
VALUES(BB_INGREDIENT_SEQ.NEXTVAL, '양상추', 3, 400, 20, 0);

INSERT INTO BB_INGREDIENT
VALUES(BB_INGREDIENT_SEQ.NEXTVAL, '토마토', 3, 500, 30, 0);

INSERT INTO BB_INGREDIENT
VALUES(BB_INGREDIENT_SEQ.NEXTVAL, '양파', 3, 300, 30, 0);

INSERT INTO BB_INGREDIENT
VALUES(BB_INGREDIENT_SEQ.NEXTVAL, '치즈', 4, 400, 50, 0);